### ISSUE TITLE
Request: accept HTML template as string

### ISSUE THREAD

**Issue by derrickb** [haifeng2013/rollup-plugin-bundle-html#1]
It would be convenient to be able to supply a short string, eg:

`"<html><head></head></html>"`

to the plugin instead of needing to have a file.

**Comment by haifeng2013** [comment]
hey @derrickb 

Thanks for your feedback!
I'll add the feature and update plugin shortly.

**Comment by haifeng2013** [comment]
new version is published!

**Comment by derrickb** [comment]
Thank you!
