### ISSUE TITLE
Compatibility with rollup@1.x.x

### ISSUE THREAD

**Issue by doktordata** [haifeng2013/rollup-plugin-bundle-html#3]
Since `rollup@1.x.x` the `onwrite` hook is deprecated which generates this error:

```
(!) html plugin: The onwrite hook used by plugin html is deprecated. The generateBundle hook should be used instead.
```
See https://github.com/rollup/rollup/pull/2409

**Comment by haifeng2013** [comment]
onwrite hook is replaced with writeBundle hook.
